spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/housing
    username: postgres
    password: 1
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: always
  liquibase:
    changelog: classpath:/db/changelog/db.changelog-master.xml
